# Generated by Django 6.1.1 on 2026-10-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_leao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='pix',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave Pix'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='vinculo',
            field=models.CharField(blank=True, choices=[('CELETISTA', 'Celetista'), ('ESTAGIARIO', 'Estagiário'), ('PJ', 'Pessoa Jurídica'), ('OUTRO', 'Outro')], default='CELETISTA', max_length=50, null=True, verbose_name='Vínculo Empregatício'),
        ),
    ]
